### PR TITLE
update template to polish things up

### PR DESCRIPTION
**Pull request by kmasiello**
- renamed some of the background images to be more logical
- incorporated some polish taken on from the positconfslides

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you so much!! Should we move this to a proper repo location?

**Comment by kmasiello** [comment]
sounds like a plan.  I can just drop my repo into /rstudio, unless you want
to merge the PR and transfer.  All the same to me.

**Comment by cscheid** [comment]
I think starting from a fresh repo/history is probably cleanest, since there's nothing interesting in this one, and folks don't need to see a personal repo (I don't think!)

**Comment by kmasiello** [comment]
Done! Migrated work over.

**Pull request closed without merging**
